import type { AppDefinition } from '@/types'

export const APP_REGISTRY: Record<string, AppDefinition> = {
  notepad: {
    id: 'notepad',
    name: 'Notepad',
    icon: 'FileText',
    permissions: ['filesystem.read', 'filesystem.write'],
    defaultWidth: 680,
    defaultHeight: 520,
    minWidth: 400,
    minHeight: 300,
  },
  terminal: {
    id: 'terminal',
    name: 'SlothShell',
    icon: 'Terminal',
    permissions: [],
    defaultWidth: 700,
    defaultHeight: 480,
    minWidth: 480,
    minHeight: 300,
  },
  games: {
    id: 'games',
    name: 'Games',
    icon: 'Gamepad2',
    permissions: ['games.read', 'games.write'],
    defaultWidth: 640,
    defaultHeight: 520,
    minWidth: 400,
    minHeight: 400,
  },
  files: {
    id: 'files',
    name: 'Files',
    icon: 'Folder',
    permissions: ['filesystem.read', 'filesystem.write', 'filesystem.delete'],
    defaultWidth: 720,
    defaultHeight: 500,
    minWidth: 500,
    minHeight: 350,
  },
  settings: {
    id: 'settings',
    name: 'Settings',
    icon: 'Settings',
    permissions: ['settings.read', 'settings.write'],
    defaultWidth: 700,
    defaultHeight: 530,
    minWidth: 500,
    minHeight: 400,
  },
  analytics: {
    id: 'analytics',
    name: 'Analytics',
    icon: 'BarChart2',
    permissions: [],
    defaultWidth: 740,
    defaultHeight: 540,
    minWidth: 500,
    minHeight: 400,
  },
  ai: {
    id: 'ai',
    name: 'Sloth AI',
    icon: 'Bot',
    permissions: [],
    defaultWidth: 680,
    defaultHeight: 560,
    minWidth: 480,
    minHeight: 400,
  },
  cemetery: {
    id: 'cemetery',
    name: 'Project Cemetery',
    icon: 'Skull',
    permissions: [],
    defaultWidth: 700,
    defaultHeight: 520,
    minWidth: 480,
    minHeight: 380,
  },
  processes: {
    id: 'processes',
    name: 'Process Manager',
    icon: 'Cpu',
    permissions: [],
    defaultWidth: 720,
    defaultHeight: 500,
    minWidth: 500,
    minHeight: 350,
  },
  google: {
    id: 'google',
    name: 'Google',
    icon: 'Globe',
    permissions: [],
    defaultWidth: 1000,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 400,
  },
  todo: {
    id: 'todo',
    name: 'Tasks',
    icon: 'ListTodo',
    permissions: [],
    defaultWidth: 480,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 500,
  },
}

export const DESKTOP_APPS = [
  'files',
  'google',
  'todo',
]
